### ISSUE TITLE
How to identify the area of interest (VISp) region of Allen-1/Allen-2 data

### ISSUE THREAD

**Issue by jincanke** [almaan/spacetx#1]
Hi Almaan,
Thanks for sharing the data, I want to reuse Allen-1 and Allen-2 data and try the spatial project(topic-2) of single-cell_sib_scilifelab_2021, but I don't know how to select the spots of VISp region.  Is it possible to share the code or spatial location of this area?  Thank you very much.

**Comment by almaan** [comment]
Hi @jincanke, 

so I didn't use a specific script for this particular selection, but wrote a small interactive program that allowed for interactive selection. However, in the course you mentioned we used Napari, and provided a notebook with instructions for selection of an area of interest, this can be accessed: [HERE](https://github.com/NBISweden/single-cell_sib_scilifelab_2021/blob/main/project_spatial/notebooks/napari-test.ipynb). Hopefully that should clarify things.

Good luck with the analysis!

/A

**Comment by jincanke** [comment]
Thank you, almaan!

**Comment by almaan** [comment]
My pleasure! Assuming this addressed your question, I'm also going to close this issue now! :)
